# Generated by Django 5.2.15 on 2026-06-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherrecord',
            name='city',
            field=models.CharField(default='New York', max_length=100),
        ),
        migrations.AlterField(
            model_name='weatherrecord',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='weatherrecord',
            unique_together={('date', 'city')},
        ),
    ]
