# Generated by Django 5.2.15 on 2026-06-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_weatherrecord_city_alter_weatherrecord_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherrecord',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
